### ISSUE TITLE
Motor test Y

### ISSUE THREAD

**Issue by rbakerohio** [JJulio/AHRobot#1]
I think the motor test y folder and motor test y.ino is missing from the  utilities folder

**Comment by rbakerohio** [comment]
Thanks Jose. I'm almost ready to play. Just a little tweaking to do yet. Fun project!

**Comment by JJulio** [comment]
You are right, I will take a look. I am now correcting some bugs and making some tweaks so I will update code soon (take a look in some days)
Thanks!
  Jose

**Comment by JJulio** [comment]
Updated the Motor Y Test!
