### ISSUE TITLE
Coding Error

### ISSUE THREAD

**Issue by seniorgroup2014** [JJulio/AHRobot#2]
![image](https://f.cloud.github.com/assets/6878610/2352792/2a1f245c-a592-11e3-8d7f-ad6c1add8836.png)

Hi Julio,

Great project! I am trying to build it for my senior design group and I run into some code error for the camera. I would appreciate it if you could look at the link above and help me out when you get a chance. 

I am having an issue with this line
serialPort = CreateFile(portSpecifier,GENERIC_READ|GENERIC_WRITE,0,NULL,OPEN_EXISTING,0,NULL);
Thanks!

**Comment by rbakerohio** [comment]
I'm not getting that error. I have tested the build and have had no camera issues. Are you using the same com port that is assigned to your arduino or did you possibly not edit  the com port in the batch file when you calibrated the colors for the puck and pusher?

**Comment by JJulio** [comment]
Hi,
I used Visual Studio Express edition to compile the code. I needed to use wchar_t variables for strings becuase it uses extended character sets. I think you should change the wchar_t\* with standard char\* and should work for your compiler. Maybe you will need to substitute this on other parts of code and use the "char" variable type.

**Comment by seniorgroup2014** [comment]
Good Morning Julio 

My team is having issue connecting the motors to the ramps board is there anyway you can send me a picture of how the pins are connected on the board. You can email me through here.

Thank you for the help

Gabriel Alvarez
Senior Design Team 23

**Comment by rbakerohio** [comment]
This may help .

On Thursday, March 27, 2014 10:03 AM, seniorgroup2014 notifications@github.com wrote:

Good Morning Julio 

My team is having issue connecting the motors to the ramps board is there anyway you can send me a picture of how the pins are connected on the board. You can email me through here.

Thank you for the help

Gabriel Alvarez
Senior Design Team 23

**Comment by seniorgroup2014** [comment]
sorry i didnt receive anything with the email

**Comment by JJulio** [comment]
Hi,
I will try to update the build manual with new photos of the connection between components on the RAMPS board this weekend.
Did you resolve the problem with the serial port? (first issue)

Jose.

**Comment by seniorgroup2014** [comment]
Yes the serial port error was fixed but the issue my team is having is connecting the ramps and sensors and giving power to the ramps 

Gabriel E. Alvarez
305-804-4495
